apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uxl1e2wxs-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uxl1e2wxs-java-springboot-gitops